@VisitorManagement.Api_HostAddress = http://localhost:5155

GET {{VisitorManagement.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{VisitorManagement.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
